baseURL = "https://eistreff-waldbronn.de/"
languageCode = "de"
title = "Eistreff Waldbronn"
theme = "eistreff"

[menu]
  [[menu.main]]
    name = "Eishalle"
    url = "/eishalle"
    weight = 10
  [[menu.main]]
    name = "Events"
    url = "/events"
    weight = 20
  [[menu.main]]
    name = "Business Club"
    url = "/business-club"
    weight = 30
  [[menu.main]]
    name = "Eissport"
    url = "/eissport"
    weight = 40
  [[menu.main]]
    name = "Über uns"
    url = "/about"
    weight = 50

  [[menu.footer]]
    name = "Kontakt"
    url = "/kontakt"
    weight = 10
  [[menu.footer]]
    name = "Hallenordnung"
    url = "/hallenordnung"
    weight = 20
  [[menu.footer]]
    name = "Datenschutz"
    url = "/datenschutz"
    weight = 30
  [[menu.footer]]
    name = "Impressum"
    url = "/impressum"
    weight = 40
